server:
  port: 8083

management:
  server:
    port: 8092
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  cache:
    size: 100
    expiry: 5
  rest:
    api:
      prefix: /api

yandexweather:
  headerKey: "X-Yandex-API-Key"
  headerValue: "${tokenYandex}"
  url: "https://api.weather.yandex.ru/v2/forecast?lat=%s&lon=%s"