server:
  port: 8080

management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  rest:
    api:
      prefix: /api


openweather-client:
  url: "http://localhost:8081/api/v1/weatherInfo"